#pragma once

#ifdef DLL_INJECT
#define TranslateItem ((void(__cdecl*)(ITEM_INFO* item, int x, int y, int z)) 0x0044A060)
#define GetChange ((int(__cdecl*)(ITEM_INFO* item, ANIM_STRUCT* anim)) 0x00449FC0)
#define AnimateItem ((void(__cdecl*)(ITEM_INFO* item)) 0x00449B90)
#define GetRandomControl ((int(__cdecl*)(void)) 0x00490EE0)
#define GetRandomDraw ((int(__cdecl*)(void)) 0x00490F00)
#define SeedRandomControl ((void(__cdecl*)(int seed)) 0x00490F20)
#define SeedRandomDraw ((void(__cdecl*)(int seed)) 0x00490F30)
#define DoRayBox ((BOOL(__cdecl*)(GAME_VECTOR *start, GAME_VECTOR *end, short *box, PHD_3DPOS *itemorstatic_pos, PHD_VECTOR *hitpos, short close_itemNumber)) 0x0044CDF0)
#define LOS  ((int(__cdecl*)(GAME_VECTOR *src, GAME_VECTOR *target)) 0x0044BBE0)
#define xLOS ((int(__cdecl*)(GAME_VECTOR *src, GAME_VECTOR *target)) 0x0044BC80)
#define zLOS ((int(__cdecl*)(GAME_VECTOR *src, GAME_VECTOR *target)) 0x0044BFD0)
#define ObjectOnLOS2 ((int(__cdecl*)(GAME_VECTOR* start, GAME_VECTOR* end, PHD_VECTOR* vec, MESH_INFO** mesh)) 0x0044CBE0)
#define GetFloor ((FLOOR_INFO*(__cdecl*)(int x, int y, int z, short* roomNumber)) 0x0044A1A0)
#define GetWaterHeight ((int(__cdecl*)(int x, int y, int z, short roomNumber)) 0x0044A390)
#define GetFloorHeight ((int(__cdecl*)(FLOOR_INFO* floor, int x, int y, int z)) 0x0044A530)
#define GetCeiling ((int(__cdecl*)(FLOOR_INFO* floor, int x, int y, int z)) 0x0044B690)
#define GetWaterDepth ((int(__cdecl*)(int x, int y, int z, short roomNumber)) 0x00432BF0)
#define TestTriggers ((void(__cdecl*)(short* data, BOOL heavy, short heavy_flags)) 0x0044AB50)
#define TriggerActive ((BOOL(__cdecl*)(ITEM_INFO* item)) 0x0044B620)
#define ResetHUB ((void(__cdecl*)(BOOL saveLara)) 0x0045A100)
#define ControlPhase ((int(__cdecl*)(int nframe, BOOL demo_mode)) 0x00449410)
#define UpdateLightning ((void(__cdecl*)(void)) 0x00451180)
#define TestTriggerXYZ ((void(__cdecl*)(int x, int y, int z, short roomNumber, short heavy, short heavy_flags)) 0x00461CA0)
#endif