#pragma once

#define VAR_U_(address, type)			(*(type*)(address))				// uninitialized variable
#define VAR_I_(address, type, value)	(*(type*)(address))				// initialized variable (value is just for info)
#define ARRAY_(address, type, length)	(*(type(*)length)(address))		// array (can be multidimensional)


///===============================///
///             MATRIX            ///
///===============================///

#define phd_mxptr                           VAR_U_(0x007E71D8, int*)
#define w2v_matrix                          ARRAY_(0x00753CC8, int, [12])

///===============================///
///             OTHER             ///
///===============================///

#define dword_4BF300                        VAR_I_(0x004BF300, int, 0)

#define phd_laralefthand                    ARRAY_(0x0080E9C0, int, [12])
#define phd_lararighthand                   ARRAY_(0x0080E930, int, [12])
#define phd_left                            VAR_U_(0x00753C78, int)
#define phd_top                             VAR_U_(0x00753C30, int)
#define phd_right                           VAR_U_(0x007540D0, int)
#define phd_bottom                          VAR_U_(0x00753C70, int)
#define phd_winxmax                         VAR_U_(0x00753C84, short)
#define phd_winymax                         VAR_U_(0x00753CA8, short)
#define phd_persp                           VAR_U_(0x00753C74, int)
#define phd_znear                           VAR_U_(0x00753C88, int)
#define phd_zfar                            VAR_U_(0x00753C60, int)
#define phd_centerx                         VAR_U_(0x00753C4C, int)
#define phd_centery                         VAR_U_(0x00753C50, int)
#define phd_winwidth                        VAR_U_(0x00753CF8, int)
#define phd_winheight                       VAR_U_(0x00753C48, int)
#define rcossin_tbl                         ARRAY_(0x004B56A4, short, [8192])
#define CurrentRoom                         VAR_U_(0x007FDF6C, int)
#define invnframes                          VAR_U_(0x007FE734, int)
#define NumRPickups                         VAR_U_(0x007F5708, int)
#define byte_7FD1DC                         VAR_U_(0x007FD1DC, char)
#define byte_7F5700                         VAR_U_(0x007F5700, char)
#define SequenceUsed                        VAR_U_(0x007F570C, short)
#define CurrentSequence                     VAR_I_(0x007F5700, BYTE, 0)
#define Sequences                           ARRAY_(0x007F573C, BYTE, [3])
#define SequenceResult                      ARRAY_(0x007F5720, BYTE, [3][3][3])
#define gf_level_flags                      VAR_U_(0x007FD260, int)
#define gf_num_mips                         VAR_U_(0x004BF66B, BYTE)
#define gf_mips                             ARRAY_(0x007FD280, BYTE, [])
#define LevelNow                            VAR_U_(0x007FD290, char)
#define level_items                         VAR_I_(0x004BF68C, int, 0)
#define nAIObjects                          VAR_U_(0x007FD200, short)
#define AIObjects                           VAR_U_(0x007FD204, AIOBJECT*)
#define GnPlayingCutseq                     VAR_I_(0x004BFC80, int, 0)
#define bDisableLaraControl                 VAR_I_(0x004BF6F0, int, 0)
#define gf_game_mode                        VAR_U_(0x004AF451, char, 1)
#define camera_number_frames                VAR_U_(0x007FE854, int)
#define outside                             VAR_U_(0x007FD300, int)
#define outside_top                         VAR_U_(0x007FE150, int)
#define outside_left                        VAR_U_(0x007FE118, int)
#define outside_right                       VAR_U_(0x007FE138, int)
#define outside_bottom                      VAR_U_(0x007FDF58, int)
#define underwater                          VAR_U_(0x007FE12C, int)
#define bound_list                          ARRAY_(0x004BF424, int, [128])
#define bound_start                         VAR_I_(0x004BF628, int, 0)
#define bound_end                           VAR_I_(0x004BF62C, int, 0)
#define draw_rooms                          ARRAY_(0x007FDF80, short, [200])
#define draw_rooms_number                   VAR_U_(0x007FD304, int)
#define RenderTypeDebug                     VAR_U_(0x007E71E0, int)
#define gf_lens_flare                       VAR_U_(0x007FD2A0, PHD_VECTOR)
#define BinocularRange                      VAR_I_(0x004BF3E4, int, 0)
#define LaserSightActive                    VAR_I_(0x004BF37E, int, 0)
#define gf_mirror_room                      VAR_U_(0x007FD250, unsigned char)
#define Lightning                           ARRAY_(0x007FE130, unsigned short, [])
#define LightningDraw                       VAR_U_(0x007FDF68, short)
#define LightningRandom                     VAR_U_(0x007FDF5C, short)
#define LightningStart                      VAR_U_(0x007FE14C, short)
#define LightningTimer                      VAR_I_(0x004BF624, short, 0)
#define gfLayer1Red							VAR_U_(0x007FD2F8, unsigned short)
#define gfLayer1Green						VAR_U_(0x007FD2FA, unsigned short)
#define gfLayer1Blue						VAR_U_(0x007FD2FC, unsigned short)
#define gfLayer1Color                       VAR_U_(0x007FD264, unsigned short)
#define gfLayer1Color2                      VAR_U_(0x007FE128, unsigned short)
#define gfLayer2Color                       VAR_U_(0x007FD25C, unsigned short)
#define gfLayer2Color2                      VAR_U_(0x007FDF5E, unsigned short)
#define CurrentDeathItemRoom                VAR_U_(0x007FDF50, short)
#define CurrentDeathItemColor               VAR_I_(0x004AD7D4, unsigned int, 0x0FF000000)
#define vbufdoor                            ARRAY_(0x007FDF20, DOOR_VBUF, [4])
#define GunFlashColor                       VAR_U_(0x005C047C, unsigned int)
#define next_firesparks						VAR_I_(0x004ADF5C, int, 0)
#define next_smokesparks					VAR_I_(0x004BF390, int, 0)
#define next_gunshell						VAR_I_(0x004BF398, int, 0)
#define next_bubbles						VAR_I_(0x004BF39C, int, 0)
#define next_drip							VAR_I_(0x004BF3A0, int, 0)
#define next_debris							VAR_I_(0x004BF358, int, 0)
#define next_blood							VAR_I_(0x004BF394, int, 0)
#define dummy_rotation                      ARRAY_(0x004BF630, short, [12])

#define wibble                              VAR_I_(0x004BF360, int, 0)
#define fire_bounds                         ARRAY_(0x0080D7C0, short, [6])
#define dynamics                            ARRAY_(0x00804860, DYNAMIC, [MAX_DYNAMICS])
#define lara								VAR_U_(0x0080DFE0, LARA_INFO)
#define lara_item                           VAR_U_(0x0080E13C, ITEM_INFO*)
#define items                               VAR_U_(0x007FE28C, ITEM_INFO*)
#define objects                             ARRAY_(0x0052B850, OBJECT_INFO, [NUMBER_OBJECTS])
#define static_objects                      ARRAY_(0x005333C0, STATIC_INFO, [NUMBER_STATIC_OBJECTS])
#define meshes                              VAR_U_(0x00533A80, short**)
#define rooms                               VAR_U_(0x00533A64, ROOM_INFO*)
#define anims                               VAR_U_(0x00533A68, ANIM_STRUCT*)
#define bones                               VAR_U_(0x00533A88, int*)
#define frames                              VAR_U_(0x00533A84, short*)
#define overlap                             VAR_U_(0x007FE9A8, short*)
#define boxes                               VAR_U_(0x007FE9B0, BOX_INFO*)
#define floor_data                          VAR_U_(0x00533A78, short*)
#define camera                              VAR_U_(0x007FE820, CAMERA_INFO) // not finished !!!
#define effects                             VAR_U_(0x008012E0, FX_INFO*)
#define flip_status                         VAR_U_(0x007FE218, int)
#define ground_zone                         ARRAY_(0x007FE980, short*, [5][2])
#define gunshells                           ARRAY_(0x007FF680, GUNSHELL_STRUCT, [MAX_GUNSHELLS])
#define sparks                              ARRAY_(0x00801400, SPARKS, [MAX_SPARKS])
#define gunflashes                          ARRAY_(0x00800CE0, GUNFLASH_STRUCT, [MAX_GUNFLASH])
#define firesparks                          ARRAY_(0x00800600, FIRE_SPARKS, [MAX_FIRE_SPARKS])
#define smokesparks                         ARRAY_(0x007FF100, SMOKE_SPARKS, [MAX_SMOKESPARKS])
#define debris                              ARRAY_(0x00808FA0, DEBRIS_STRUCT, [MAX_DEBRIS])
#define blood                               ARRAY_(0x00800180, BLOOD_STRUCT, [MAX_BLOOD])
#define splashes                            ARRAY_(0x00804E80, SPLASH_STRUCT, [MAX_SPLASHES])
#define ripples                             ARRAY_(0x00801300, RIPPLE_STRUCT, [MAX_RIPPLES])
#define bubbles                             ARRAY_(0x00800920, BUBBLE_STRUCT, [MAX_BUBBLES])
#define drips                               ARRAY_(0x00800DC0, DRIP_STRUCT, [MAX_DRIPS])
#define shockwave                           ARRAY_(0x007FF960, SHOCKWAVE_STRUCT, [MAX_SHOCKWAVE])
#define firelists                           ARRAY_(0x007FFF60, FIRE_LIST, [MAX_FIRE_LIST])