#pragma once
#ifdef DLL_INJECT

#define VAR_U_(address, type)            (*(type*)(address))                // uninitialized variable
#define VAR_I_(address, type, value)    (*(type*)(address))                // initialized variable (value is just for info)
#define ARRAY_(address, type, length)    (*(type(*)length)(address))        // array (can be multidimensional)


/// official app address
#define App                                VAR_U_(0x00753980, WINAPP)

///===============================///
///             MATRIX            ///
///===============================///

#define phd_mxptr                           VAR_U_(0x007E71D8, int*)
#define w2v_matrix                          ARRAY_(0x00753CC8, int, [12])
#define IM_ptr                              VAR_U_(0x007FE124, int*)
#define IM_rate                             VAR_U_(0x007FE120, int)
#define IM_frac                             VAR_U_(0x007FDF54, int)

///===============================///
///             OTHER             ///
///===============================///

#define lara_matrix_normal_type2            ARRAY_(0x0080EA00, int, [12][12])
#define lara_matrix_holsters_type2          ARRAY_(0x0080E720, int, [12][12]) // first [12] = joint, second [12] = matrix
#define lara_matrix_normal                  VAR_U_(0x0080EA00, LARA_MATRIX)
#define lara_matrix_holsters                VAR_U_(0x0080E720, LARA_MATRIX)
#define phd_laralefthand                    ARRAY_(0x0080E9C0, int, [12])
#define phd_lararighthand                   ARRAY_(0x0080E930, int, [12])
#define phd_left                            VAR_U_(0x00753C78, int)
#define phd_top                             VAR_U_(0x00753C30, int)
#define phd_right                           VAR_U_(0x007540D0, int)
#define phd_bottom                          VAR_U_(0x00753C70, int)
#define phd_winxmax                         VAR_U_(0x00753C84, short)
#define phd_winymax                         VAR_U_(0x00753CA8, short)
#define phd_persp                           VAR_U_(0x00753C74, int)
#define phd_znear                           VAR_U_(0x00753C88, int)
#define phd_zfar                            VAR_U_(0x00753C60, int)
#define phd_centerx                         VAR_U_(0x00753C4C, int)
#define phd_centery                         VAR_U_(0x00753C50, int)
#define phd_winwidth                        VAR_U_(0x00753CF8, int)
#define phd_winheight                       VAR_U_(0x00753C48, int)
#define rcossin_tbl                         ARRAY_(0x004B56A4, short, [8192])
#define CurrentRoom                         VAR_U_(0x007FDF6C, int)
#define invnframes                          VAR_U_(0x007FE734, int)
#define NumRPickups                         VAR_U_(0x007F5708, int)
#define byte_7FD1DC                         VAR_U_(0x007FD1DC, char)
#define byte_7F5700                         VAR_U_(0x007F5700, char)
#define SequenceUsed                        VAR_U_(0x007F570C, short)
#define CurrentSequence                     VAR_I_(0x007F5700, BYTE, 0)
#define Sequences                           ARRAY_(0x007F573C, BYTE, [3])
#define SequenceResult                      ARRAY_(0x007F5720, BYTE, [3][3][3])
#define gf_level_flags                      VAR_U_(0x007FD260, int)
#define gf_num_mips                         VAR_U_(0x004BF66B, BYTE)
#define gf_mips                             ARRAY_(0x007FD280, BYTE, [])
#define LevelNow                            VAR_U_(0x007FD290, char)
#define level_items                         VAR_I_(0x004BF68C, int, 0)
#define nAIObjects                          VAR_U_(0x007FD200, short)
#define AIObjects                           VAR_U_(0x007FD204, AIOBJECT*)
#define GnPlayingCutseq                     VAR_I_(0x004BFC80, int, 0)
#define bDisableLaraControl                 VAR_I_(0x004BF6F0, int, 0)
#define gf_game_mode                        VAR_U_(0x004AF451, char, 1)
#define camera_number_frames                VAR_U_(0x007FE854, int)
#define outside                             VAR_U_(0x007FD300, int)
#define outside_top                         VAR_U_(0x007FE150, int)
#define outside_left                        VAR_U_(0x007FE118, int)
#define outside_right                       VAR_U_(0x007FE138, int)
#define outside_bottom                      VAR_U_(0x007FDF58, int)
#define underwater                          VAR_U_(0x007FE12C, int)
#define bound_list                          ARRAY_(0x004BF424, int, [128])
#define bound_start                         VAR_I_(0x004BF628, int, 0)
#define bound_end                           VAR_I_(0x004BF62C, int, 0)
#define draw_rooms                          ARRAY_(0x007FDF80, short, [200])
#define draw_rooms_number                   VAR_U_(0x007FD304, int)
#define RenderTypeDebug                     VAR_U_(0x007E71E0, int)
#define gf_lens_flare                       VAR_U_(0x007FD2A0, PHD_VECTOR)
#define BinocularRange                      VAR_I_(0x004BF3E4, int, 0)
#define LaserSight                          VAR_I_(0x004BF3F0, int, 0)
#define LaserSightActive                    VAR_I_(0x004BF37E, int, 0)
#define LaserSightPos                       VAR_U_(0x00800160, PHD_VECTOR)
#define gf_mirror_room                      VAR_U_(0x007FD250, unsigned char)
#define Lightning                           ARRAY_(0x007FE130, unsigned short, [])
#define LightningDraw                       VAR_U_(0x007FDF68, short)
#define LightningRandom                     VAR_U_(0x007FDF5C, short)
#define LightningStart                      VAR_U_(0x007FE14C, short)
#define LightningTimer                      VAR_I_(0x004BF624, short, 0)
#define gfLayer1Red                         VAR_U_(0x007FD2F8, unsigned short)
#define gfLayer1Green                       VAR_U_(0x007FD2FA, unsigned short)
#define gfLayer1Blue                        VAR_U_(0x007FD2FC, unsigned short)
#define gfLayer1Color                       VAR_U_(0x007FD264, unsigned short)
#define gfLayer1Color2                      VAR_U_(0x007FE128, unsigned short)
#define gfLayer2Color                       VAR_U_(0x007FD25C, unsigned short)
#define gfLayer2Color2                      VAR_U_(0x007FDF5E, unsigned short)
#define CurrentDeathItemRoom                VAR_U_(0x007FDF50, short)
#define CurrentDeathItemColor               VAR_I_(0x004AD7D4, unsigned int, 0xFF000000)
#define TargetType                          VAR_U_(0x007FE9B8, short) // use TARGET_TYPE enum
#define vbufdoor                            ARRAY_(0x007FDF20, DOOR_VBUF, [4])
#define GunFlashColor                       VAR_U_(0x005C047C, unsigned int)
#define next_firesparks                     VAR_I_(0x004ADF5C, int, 0)
#define next_smokesparks                    VAR_I_(0x004BF390, int, 0)
#define next_gunshell                       VAR_I_(0x004BF398, int, 0)
#define next_bubbles                        VAR_I_(0x004BF39C, int, 0)
#define next_drip                           VAR_I_(0x004BF3A0, int, 0)
#define next_debris                         VAR_I_(0x004BF358, int, 0)
#define next_blood                          VAR_I_(0x004BF394, int, 0)
#define dummy_rotation                      ARRAY_(0x004BF630, short, [12])
#define Setting_MusicVolume                 VAR_U_(0x004B38AC, int)
#define Setting_SFXVolume                   VAR_U_(0x004B38B0, int)
#define force_fixed_camera                  VAR_U_(0x007FE8C0, bool)
#define baddie_slots                        VAR_U_(0x007FD1FC, CREATURE_INFO*)
#define trigger_index                       VAR_U_(0x007FE248, short*)
#define number_boxes                        VAR_U_(0x007FE9B4, int)
#define SmokeCountL                         VAR_U_(0x00804E68, int)
#define SmokeCountR                         VAR_U_(0x00804E6C, int)
#define SmokeWeapon                         VAR_U_(0x00804F20, int)
#define TrInput                             VAR_U_(0x00535704, int)
///#define EntityBlindTimer                    VAR_U_(0x0080E136, char)
#define EnemyOffset                         ARRAY_(0x004AED00, BITE_INFO, [11])
#define level_data                          VAR_U_(0x005333A4, char*)
#define fp_level                            VAR_U_(0x00533A74, LPFILE)
#define savegame_ammoused                   VAR_U_(0x007F785A, int)
#define savegame_ammohit                    VAR_U_(0x007F785E, int)
#define savegame_kills                      VAR_U_(0x007F7876, short)
#define height_type                         VAR_U_(0x007FE290, int) // height_types enum
#define interpolated_bounds                 ARRAY_(0x007FE140, short, [6])
#define LeftClimbTab                        ARRAY_(0x004AD800, short, [4])
#define RightClimbTab                       ARRAY_(0x004AD808, short, [4])
#define LeftIntRightExtTab                  ARRAY_(0x004AD838, short, [4])
#define LeftExtRightIntTab                  ARRAY_(0x004AD840, short, [4])
#define SelectedObject                      VAR_I_(0x004AE06C, int, NO_ITEM)
#define current_pendulum                    VAR_U_(0x007FD1A0, PENDULUM)
#define FXType                              VAR_U_(0x007FE7E0, short)
#define number_los_rooms                    VAR_I_(0x004BF418, int, 0)
#define los_rooms                           ARRAY_(0x007FE260, short, [20])
#define ClosestItem                         VAR_U_(0x007FE2E0, int)
#define ClosestDist                         VAR_U_(0x007FE380, int)
#define ClosestCoord                        VAR_U_(0x007FE330, PHD_VECTOR)
#define SmashedMeshCount                    VAR_I_(0x004BF3FE, short, 0)
#define SmashedMeshRoom                     ARRAY_(0x007FE360, short, [16])
#define SmashedMesh                         ARRAY_(0x007FE7A0, GAME_VECTOR*, [4])
#define ShatterItem                         VAR_U_(0x007FE960, SHATTER_ITEM)
#define lara_shadow_bbox                    VAR_U_(0x0080E710, short*)
#define vertex_buffer                       VAR_U_(0x00753910, LPDIRECT3DVERTEXBUFFER)

#define wibble                              VAR_I_(0x004BF360, int, 0)
#define fire_bounds                         ARRAY_(0x0080D7C0, short, [6])
#define dynamics                            ARRAY_(0x00804860, DYNAMIC, [MAX_DYNAMICS])
#define lara                                VAR_U_(0x0080DFE0, LARA_INFO)
#define lara_item                           VAR_U_(0x0080E13C, ITEM_INFO*)
#define items                               VAR_U_(0x007FE28C, ITEM_INFO*)
#define objects                             ARRAY_(0x0052B850, OBJECT_INFO, [NUMBER_OBJECTS])
#define static_objects                      ARRAY_(0x005333C0, STATIC_INFO, [NUMBER_STATIC_OBJECTS])
#define mesh_base                           VAR_U_(0x00533A7C, short*)
#define meshes                              VAR_U_(0x00533A80, short**)
#define rooms                               VAR_U_(0x00533A64, ROOM_INFO*)
#define anims                               VAR_U_(0x00533A68, ANIM_STRUCT*)
#define changes                             VAR_U_(0x00533A6C, CHANGE_STRUCT*)
#define ranges                              VAR_U_(0x00533A70, RANGE_STRUCT*)
#define commands                            VAR_U_(0x00533A8C, short*)
#define bones                               VAR_U_(0x00533A88, int*)
#define frames                              VAR_U_(0x00533A84, short*)
#define overlaps                            VAR_U_(0x007FE9A8, short*)
#define boxes                               VAR_U_(0x007FE9B0, BOX_INFO*)
#define floor_data                          VAR_U_(0x00533A78, short*)
#define camera                              VAR_U_(0x007FE820, CAMERA_INFO)
#define effects                             VAR_U_(0x008012E0, FX_INFO*)
#define flip_status                         VAR_U_(0x007FE218, int)
///#define weapons                          ARRAY_(0x004AD848, WEAPON_INFO, [8])
///#define pistols_table                    ARRAY_(0x004AD820, PISTOL_DEF, [4])
#define ground_zone                         ARRAY_(0x007FE980, short*, [5][2]) // [ZONE_TYPE][flip_status] (return short*)
#define gunshells                           ARRAY_(0x007FF680, GUNSHELL_STRUCT, [MAX_GUNSHELLS])
#define sparks                              ARRAY_(0x00801400, SPARKS, [MAX_SPARKS])
#define gunflashes                          ARRAY_(0x00800CE0, GUNFLASH_STRUCT, [MAX_GUNFLASH])
#define firesparks                          ARRAY_(0x00800600, FIRE_SPARKS, [MAX_FIRE_SPARKS])
#define smokesparks                         ARRAY_(0x007FF100, SMOKE_SPARKS, [MAX_SMOKESPARKS])
#define debris                              ARRAY_(0x00808FA0, DEBRIS_STRUCT, [MAX_DEBRIS])
#define blood                               ARRAY_(0x00800180, BLOOD_STRUCT, [MAX_BLOOD])
#define splashes                            ARRAY_(0x00804E80, SPLASH_STRUCT, [MAX_SPLASHES])
#define ripples                             ARRAY_(0x00801300, RIPPLE_STRUCT, [MAX_RIPPLES])
#define bubbles                             ARRAY_(0x00800920, BUBBLE_STRUCT, [MAX_BUBBLES])
#define drips                               ARRAY_(0x00800DC0, DRIP_STRUCT, [MAX_DRIPS])
#define shockwave                           ARRAY_(0x007FF960, SHOCKWAVE_STRUCT, [MAX_SHOCKWAVE])
#define firelists                           ARRAY_(0x007FFF60, FIRE_LIST, [MAX_FIRE_LIST])
#define ropes                               ARRAY_(0x007FB4C0, ROPE_STRUCT, [MAX_ROPES])
#define collide_item                        ARRAY_(0x00804F80, ITEM_INFO*, [256]) // not sure for the size !
#define collide_meshes                      ARRAY_(0x00805380, MESH_INFO*, [256]) // not sure for the size !
#define effect_routines                     ARRAY_(0x004ADE8C, EFFECT_ROUTINES_STRUCT, [47])



/// INVENTORY
#define GLOBAL_invitemlastchosen            VAR_I_(0x004AE064, int, NO_ITEM)
#define GLOBAL_invEnter                     VAR_I_(0x004AE068, int, NO_ITEM)
#define GLOBAL_invitemchosen                VAR_I_(0x004AE06C, int, NO_ITEM)
#define inventry_objects_list               ARRAY_(0x004AE070, INVOBJ, [MAX_INVOBJ])
#define combine_table                       ARRAY_(0x004AEAC0, COMBINELIST, [19])
#define inventory_xpos                      VAR_I_(0x004BF3D0, int, 0)
#define inventory_ypos                      VAR_I_(0x004BF3D2, int, 0)
#define inventory_camera_angle              VAR_U_(0x007FEA50, int)
#define examine_mode                        VAR_I_(0x004BF3CC, BOOL, FALSE)
#define stats_mode                          VAR_U_(0x007FEA18, short)
#define left_debounce                       VAR_U_(0x007FE9C9, bool)
#define right_debounce                      VAR_U_(0x007FEA38, bool)
#define up_debounce                         VAR_U_(0x007FEA4C, bool)
#define down_debounce                       VAR_U_(0x007FE9F8, bool)
#define go_left                             VAR_U_(0x007FE9C1, bool)
#define go_right                            VAR_U_(0x007FE9C1, bool)
#define go_up                               VAR_U_(0x007FEA45, bool)
#define go_down                             VAR_U_(0x007FEA4B, bool)
#define select_debounce                     VAR_U_(0x007FEA43, bool)
#define deselect_debounce                   VAR_U_(0x007FEA12, bool)
#define go_select                           VAR_U_(0x007FF022, bool)
#define go_deselect                         VAR_U_(0x007FEA54, bool)
#define left_repeat                         VAR_U_(0x007FF021, bool)
#define right_repeat                        VAR_U_(0x007FEA39, bool)
#define loading_or_saving                   VAR_U_(0x007FE9CB, bool)
#define use_items                           VAR_U_(0x007FEA44, bool)
#define inv_pistols_ammo_count              VAR_I_(0x004BF3C0, short, 0)
#define inv_shotgun_ammo1_count             VAR_I_(0x004BF3AE, short, 0)
#define inv_shotgun_ammo2_count             VAR_I_(0x004BF3AC, short, 0)
#define inv_uzi_ammo_count                  VAR_I_(0x004BF3C4, short, 0)
#define inv_grenadegun_ammo1_count          VAR_I_(0x004BF3AA, short, 0)
#define inv_grenadegun_ammo2_count          VAR_I_(0x004BF3A6, short, 0)
#define inv_grenadegun_ammo3_count          VAR_I_(0x004BF3A8, short, 0)
#define inv_crossbow_ammo1_count            VAR_I_(0x004BF3B6, short, 0)
#define inv_crossbow_ammo2_count            VAR_I_(0x004BF3B4, short, 0)
#define inv_crossbow_ammo3_count            VAR_I_(0x004BF3B8, short, 0)
#define inv_revolver_ammo_count             VAR_I_(0x004BF3BE, short, 0)
#define ammo_selector_fade_val              VAR_U_(0x007FEA2A, short)
#define ammo_selector_fade_dir              VAR_U_(0x007FEA48, short)
#define combine_ring_fade_val               VAR_U_(0x007FEA16, short)
#define combine_ring_fade_dir               VAR_U_(0x007FEA40, short)
#define combine_type_flag                   VAR_U_(0x007FF020, char)
#define seperate_type_flag                  VAR_U_(0x007FEA1A, char)
#define combine_obj1                        VAR_U_(0x007FEA34, int)
#define combine_obj2                        VAR_U_(0x007FEA30, int)
#define normal_ring_fade_val                VAR_U_(0x007FEA28, short)
#define normal_ring_fade_dir                VAR_U_(0x007FEA46, short)

#endif
